cache: false
language: node_js
node_js:
  - "4.1"

install:
  - npm install

before_script:
  - npm install -g grunt-cli

script:
  - grunt build

notifications:
  email:
    on_success: never
    on_failure: change
